DELIMITER $$

CREATE EVENT IF NOT EXISTS delete_invalid_tokens_every_20_minute
ON SCHEDULE EVERY 20 MINUTE
STARTS CURRENT_TIMESTAMP
DO
BEGIN
  DELETE FROM tokens
  WHERE created_at <= DATE_SUB(NOW(), INTERVAL 7 DAY)
     OR revoked_at IS NOT NULL;
END$$

DELIMITER ;